version: '3'
services:
  web:
    container_name: web
    image: "nginx:latest"
    depends_on:
      - app
    ports:
      - "8081:80"
    environment:
      - STATE=test
    volumes:
      - "./nginx/reverse_proxy.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/html/:/var/www/html"
      - "./nginx/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d"
    networks:
      - frontend
      - backend
    links:
      - "app:app.internal"
  app:
    container_name: app
    build: ./app
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_URL="postgres://postgres:postgres@postgres.internal:5432/postgres?sslmode=disable"
    volumes:
      - ./data:/data
    networks:
      - backend
    links:
      - "postgres:postgres.internal"
  postgres:
    build: ./postgres
    container_name: "db"
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "./data:/var/lib/postgresql/"
    networks:
      - backend

networks:
  frontend:
  backend:
   internal: true
