DROP TABLE IF EXISTS app;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE app ( 
  id uuid DEFAULT uuid_generate_v4 (),
  title VARCHAR NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
